name: 直播源自动检测清理
permissions:
  contents: read
on:
  push:
  schedule:
    - cron: '0 4 * * 0' #每周日自动运行一次
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4
      - name: 安装Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: 安装依赖
        run: pip install requests
      - name: 执行检测清理脚本
        run: python check_lives.py
